import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "next hero ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="h-screen">{children}</div>
      </body>
    </html>
  );
}
