import "./globals.css";

export const metadata = {
  title: "next hero ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-red-300 px-6 py-4">
          <h6>Logo</h6>
          <ul>
            <li>About</li>
            <li>About</li>
            <li>Contact</li>
          </ul>
        </nav>
        <div className="h-screen">{children}</div>
      </body>
    </html>
  );
}
